version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    reviewers:
    - "CycloneDX/go-maintainers"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
    - "CycloneDX/go-maintainers"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
