version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: team-unify-alerts
          trusted-branch: main
          filters:
            branches:
              ignore:
                - main
